/*
 * action types
 */
export const SEARCH_FORM_CHANGED = 'SEARCH_FORM_CHANGED';
export const RESULTS_REQUESTED = 'RESULTS_REQUESTED';
export const RECEIVE_RESULTS_SUCCESS = 'RECEIVE_RESULTS_SUCCESS';
export const RECEIVE_RESULTS_FAILED = 'RECEIVE_RESULTS_FAILED';
export const RACES_REQUESTED = 'RACES_REQUESTED';
export const RECEIVE_RACES_SUCCESS = 'RECEIVE_RACES_SUCCESS';
export const RECEIVE_RACES_FAILED = 'RECEIVE_RACES_FAILED';
export const PAGE_BUTTON_CLICKED = 'PAGE_BUTTON_CLICKED';
export const RACES_TABLE_SORT_CLICKED = 'RACES_TABLE_SORT_CLICKED';
export const RESULTS_TABLE_SORT_CLICKED = 'RESULTS_TABLE_SORT_CLICKED';
export const SHOW_RESULT_LOCATIONS_CLICKED = 'SHOW_RESULT_LOCATIONS_CLICKED';
export const SHOW_RACE_LOCATIONS_CLICKED = 'SHOW_RACE_LOCATIONS_CLICKED';
export const SHOW_WINNING_TIME_CLICKED = 'SHOW_WINNING_TIME_CLICKED';
export const SHOW_MEDIAN_TIME_CLICKED = 'SHOW_MEDIAN_TIME_CLICKED';
export const SHOW_ALL_RACE_TIMES_CLICKED = 'SHOW_ALL_RACE_TIMES_CLICKED';
export const SHOW_RACE_PACES_CLICKED = 'SHOW_RACE_PACES_CLICKED';
export const SINGLE_RACE_CLICKED = 'SINGLE_RACE_CLICKED';
export const RECEIVE_SELECTED_RACE_SUCCESS = 'RECEIVE_SELECTED_RACE_SUCCESS';
export const RECEIVE_SELECTED_RACE_FAILED = 'RECEIVE_SELECTED_RACE_FAILED';
export const SINGLE_RACE_TABLE_SORT_CLICKED = 'SINGLE_RACE_TABLE_SORT_CLICKED';
